apiVersion: v1
kind: Service
metadata:
  labels:
    name: application-deployment
  name: load-balancer
spec:
  ports:
  - nodePort: 32393
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: application-deployment
  sessionAffinity: None
  type: LoadBalancer
